# Generated by Django 3.2.4 on 2021-07-07 20:41

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('Is student?', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('Is student?', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Teachers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Gradeable',
            fields=[
                ('gradeable_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('submission_datetime', models.DateTimeField(blank=True)),
                ('grading_datetime', models.DateTimeField(blank=True)),
                ('document', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('teacher_notes', models.TextField(blank=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='simpleApi.student')),
                ('teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Teacher', to='simpleApi.teacher')),
            ],
        ),
    ]
