# Generated by Django 3.2.4 on 2021-07-07 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleApi', '0002_alter_gradeable_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Is student?',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Is student?',
        ),
    ]
