# Generated by Django 3.2.4 on 2021-07-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleApi', '0003_auto_20210707_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeable',
            name='submission_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
