# Generated by Django 3.2.4 on 2021-07-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleApi', '0004_alter_gradeable_submission_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeable',
            name='grading_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
