# Generated by Django 3.2.4 on 2021-07-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleApi', '0006_auto_20210707_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeable',
            name='student',
            field=models.IntegerField(),
        ),
    ]
